# Generated by Django 5.2.1 on 2025-06-18 20:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='type',
            field=models.CharField(
                choices=[('all', 'Все'), ('bus', 'Автобус'), ('tram', 'Трамвай')],
                db_index=True,
                default=builtins.all,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
