services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd src &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:${APP_PORT}
      --workers 3
      --worker-class gthread
      --timeout 30
      --capture-output"
    container_name: qr-app
    image: ${IMAGE_APP}
    ports:
      - "127.0.0.1:8000:${APP_PORT}"
    volumes:
      - .:/src
      - static_volume:/app/src/static/
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  bot:
    build: .
    command: python src/manage.py start_bot
    container_name: qr-bot
    image: ${IMAGE_BOT}
    ports:
      - "127.0.0.1:8443:${WEBHOOK_PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17.5-alpine3.20
    container_name: qr-db
    ports:
      - "127.0.0.1:5432:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  nginx:
    build: ./nginx
    container_name: qr-nginx
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
    volumes:
      - static_volume:/app/src/static/
    depends_on:
      - app
    command: [ "nginx", "-g", "daemon off;" ]
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
