services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    container_name: qr-app
    image: ${IMAGE_APP}
    ports:
      - "127.0.0.1:8000:${APP_PORT}"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env
    restart: unless-stopped

  db:
    container_name: qr-db
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:5432:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
